services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - '${TCP_PORT}:8000'
    environment:
      - BACKEND__STATE=${BACKEND__STATE}
      - BACKEND__DJANGO_SECRET_KEY=${BACKEND__DJANGO_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - TCP_PORT=${TCP_PORT}
    depends_on:
      - postgres

  postgres:
    image: postgres:17.4
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: postgres_db
    volumes:
      - postgres_db_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4:9.2
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '8080:80'
    depends_on:
      - postgres

volumes:
  postgres_db_data: